[project]
name = "cses"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "manim>=0.19.0",
    "notebook>=7.4.4",
    "sympy>=1.14.0",
    "transitions>=0.9.3",
]
